# -*- coding: utf-8 -*-
"""ps03_ex01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfCJtp5kGwv_mXEqeJvYSneOLKCVK9Ll
"""

# Step 1: Install and import the necessary libraries
# Installing nltk if not already installed
!pip install nltk

# Importing nltk library
import nltk

# Downloading the 'punkt' tokenizer resource, which is needed for tokenization
nltk.download('punkt')

# Importing the word_tokenize function for tokenizing text into individual words
from nltk.tokenize import word_tokenize

# Step 2: Define a sample text about NLP
text = """Natural Language Processing (NLP) is a field of artificial intelligence that focuses on the interaction between computers and human languages. NLP enables machines to read, understand, and generate human language, making it possible for applications like chatbots, translation services, and sentiment analysis. The complexity of NLP lies in the nuances of language, including context, tone, and idiomatic expressions. Recent advancements, particularly with deep learning models like transformers, have significantly improved the accuracy and fluency of NLP applications."""

# Step 3: Tokenize the text
# Tokenizing the text into individual words (tokens) using word_tokenize
tokens = word_tokenize(text)
print("List of tokens:", tokens)  # Display the list of tokens

# Step 4: Count the number of tokens
# Using len() to count the number of tokens in the list
numTokens = len(tokens)
print("Number of tokens:", numTokens)  # Display the number of tokens

# Step 5: Calculate frequency distribution of tokens
# Importing FreqDist to calculate the frequency of each token
from nltk.probability import FreqDist

# Creating a frequency distribution object for the tokens
freq_dist = FreqDist(tokens)

# Displaying the frequency distribution object
print("Frequency distribution:", freq_dist)

# Iterating over the frequency distribution to display each token and its frequency
for token, frequency in freq_dist.items():
    print(f"{token}: {frequency}")